import type { Metadata } from "next";
import { Arimo, Montserrat } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/theme-provider";
// import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { ReactLenis } from "@/utils/lenis";

const arimo = Arimo({
  variable: "--font-arimo-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Awg Communications",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ReactLenis root>
        <body
          className={`${arimo.variable} ${montserrat.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* <Navbar /> */}
            {children}
            <Footer />
          </ThemeProvider>
        </body>
      </ReactLenis>
    </html>
  );
}
